//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 09:15:03 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://javabyrajasekhar.blogspot.com/spring-boot-soap-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.blogspot.javabyrajasekhar.spring_boot_soap_example;
